# This is a basic workflow to help you get started with Actions

name: autoTag

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
    paths:
    - '**.png'
  pull_request:
    branches: [ main ]
    paths:
    - '**.png'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make tag (1)
        run: echo "CURRENT_TAG=$(date +%Y.%m.%d)" >> $GITHUB_ENV
        
      - name: Make tag (2)
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.CURRENT_TAG }}
          tag_prefix: ""
