# This is a basic workflow to help you get started with Actions

name: autoRelease

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
    paths:
    - '**.png'
  pull_request:
    branches: [ main ]
    paths:
    - '**.png'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    name: stuff
    runs-on: ubuntu-latest
    steps:
      - name: Make tag (1)
        run: echo "CURRENT_TAG=$(date +%Y.%m.%d)" >> $GITHUB_ENV
        
      - name: Make tag (2)
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.CURRENT_TAG }}
          tag_prefix: ""
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          for i in */; do zip -r "${i%/}.zip" "$i" & done; wait

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
          tag_name: ${{ env.CURRENT_TAG }}
          name: ${{ env.CURRENT_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
