# This is a basic workflow to help you get started with Actions

name: autoRelease

# Controls when the action will run. 
on:
  push:
    tags: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          for i in */; do zip -r "${i%/}.zip" "$i"; done

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
